extends Node


enum
{
	# 登录成功
	LOGIN_SUCCESS = 1001,
	# 登录失败
	LOGIN_FAIL = 1002,
	# 取消登录
	LOGIN_CANCEL = 1003,
	
	# 更新成就进度成功
	UPDATE_ACHIEVEMENT_SUCCESS = 1005,
	# 更新成就进度失败
	UPDATE_ACHIEVEMENT_FAIL = 1006,
	
	# 礼品码提交成功
	GIFT_CODE_SUBMIT_SUCCESS = 1007,
	# 礼品码提交失败
	GIFT_CODE_SUBMIT_FAIL = 1008,

	# 排行榜成绩提交成功
	LEADERBOARD_SUBMIT_SUCCESS = 1009,
	# 排行榜成绩提交失败
	LEADERBOARD_SUBMIT_FAIL = 1010,
	# 排行榜分数拉取成功
	LEADERBOARD_FETCH_SCORES_SUCCESS = 1011,
	# 排行榜分数拉取失败
	LEADERBOARD_FETCH_SCORES_FAIL = 1012,
	# 排行榜当前玩家分数拉取成功
	LEADERBOARD_FETCH_CURRENT_PLAYER_SCORE_SUCCESS = 1013,
	# 排行榜当前玩家分数拉取失败
	LEADERBOARD_FETCH_CURRENT_PLAYER_SCORE_FAIL = 1014,
	# 排行榜当前玩家居中分数拉取成功
	LEADERBOARD_FETCH_CURRENT_PLAYER_CENTERED_SCORE_SUCCESS = 2013,
	# 排行榜当前玩家居中分数拉取失败
	LEADERBOARD_FETCH_CURRENT_PLAYER_CENTERED_SCORE_FAIL = 2014,
	
	# 云存档创建成功
	CLOUD_SAVE_CREATE_ARCHIVE_SUCCESS = 3013,
	# 云存档创建失败
	CLOUD_SAVE_CREATE_ARCHIVE_FAIL = 3014,
	# 云存档列表获取成功
	CLOUD_SAVE_GET_ARCHIVE_LIST_SUCCESS = 3015,
	# 云存档列表获取失败
	CLOUD_SAVE_GET_ARCHIVE_LIST_FAIL = 3016,
	# 云存档数据获取成功
	CLOUD_SAVE_GET_ARCHIVE_DATA_SUCCESS = 3017,
	# 云存档数据获取失败
	CLOUD_SAVE_GET_ARCHIVE_DATA_FAIL = 3018,
	# 云存档删除成功
	CLOUD_SAVE_DELETE_ARCHIVE_SUCCESS = 3019,
	# 云存档删除失败
	CLOUD_SAVE_DELETE_ARCHIVE_FAIL = 3020,
	# 云存档更新成功
	CLOUD_SAVE_UPDATE_ARCHIVE_SUCCESS = 3021,
	# 云存档更新失败
	CLOUD_SAVE_UPDATE_ARCHIVE_FAIL = 3022,
	# 云存档封面获取成功
	CLOUD_SAVE_GET_ARCHIVE_COVER_SUCCESS = 3023,
	# 云存档封面获取失败
	CLOUD_SAVE_GET_ARCHIVE_COVER_FAIL = 3024,
	
	# 开屏广告加载成功
	AD_SPLASH_LOAD_SUCCESS = 1021,
	# 开屏广告加载失败
	AD_SPLASH_LOAD_FAIL = 1022,
	# 开屏广告被点击
	AD_SPLASH_CLICKED = 1023,
	# 开屏广告被跳过
	AD_SPLASH_SKIPPED = 1024,
	# 开屏广告倒计时结束
	AD_SPLASH_TIME_OVER = 1025,

	# 视频激励广告加载成功
	AD_REWARD_VIDEO_LOAD_SUCCESS = 1026,
	# 视频激励广告缓存成功（如果不需要在加载成功时立即播放，可以考虑使用此信号，广告播放体验更佳）
	AD_REWARD_VIDEO_CACHE_SUCCESS = 1027,
	# 视频激励广告加载失败
	AD_REWARD_VIDEO_LOAD_FAIL = 1028,
	# 视频激励被显示
	AD_REWARD_VIDEO_SHOWN = 1029,
	# 视频激励广告被关闭
	AD_REWARD_VIDEO_CLOSED = 1030,
	# 视频激励广告播放完成
	AD_REWARD_VIDEO_COMPLETED = 1031,
	# 视频激励广告出错
	AD_REWARD_VIDEO_ERROR = 1032,
	# 视频广告被验证，可以给玩家发放奖励
	AD_REWARD_VIDEO_VERIFIED = 1033,
	# 视频激励广告被跳过
	AD_REWARD_VIDEO_SKIPPED = 1034,
	# 视频激励广告被点击
	AD_REWARD_VIDEO_CLICKED = 1035,

	# 横幅广告加载成功
	AD_BANNER_LOAD_SUCCESS = 1036,
	# 横幅广告加载失败
	AD_BANNER_LOAD_FAIL = 1037,
	# 横幅广告被显示
	AD_BANNER_SHOWN = 1038,
	# 横幅广告被关闭
	AD_BANNER_CLOSED = 1039,
	# 横幅广告被点击
	AD_BANNER_CLICKED = 1040,
	# 横幅广告中的下载按钮被点击
	AD_BANNER_DOWNLOAD_CLICKED = 1041,

	# 插屏广告加载成功
	AD_INTERSTITIAL_LOAD_SUCCESS = 1042,
	# 插屏广告加载失败
	AD_INTERSTITIAL_LOAD_FAIL = 1043,
	# 插屏广告被显示
	AD_INTERSTITIAL_SHOWN = 1044,
	# 插屏广告被关闭
	AD_INTERSTITIAL_CLOSED = 1045,
	# 插屏广告出错
	AD_INTERSTITIAL_ERROR = 1046,
	
	# 信息流广告加载成功
	AD_FEED_LOAD_SUCCESS = 1047,
	# 信息流广告加载失败
	AD_FEED_LOAD_FAIL = 1048,
	# 信息流广告渲染成功
	AD_FEED_RENDER_SUCCESS = 1049,
	# 信息流广告被显示
	AD_FEED_SHOWN = 1050,
	# 信息流广告被点击
	AD_FEED_CLICKED = 1051,
	# 信息流广告被关闭
	AD_FEED_CLOSED = 1052
}
